service: web

provider:
  name: aws
  runtime: nodejs12.x
  region: eu-west-2
  profile: brunton
  iamRoleStatements:
    - Effect: Allow
      Action:
        - s3:putObject
      Resource: 
        Fn::Join:
          - ''
          - - 'arn:aws:s3:::'
            - 'Ref': 'backupBucket'
            - '/*'

functions:
  hello:
    handler: handler.hello
    events:
      - http: GET /
  getPutUrl:
    handler: handler.getPutUrl
    events:
      - http: POST /begin-backup
    environment:
      BUCKET_NAME: ${self:custom.bucket}
plugins:
  - serverless-domain-manager

resources:
  Resources:
    backupBucket:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: ${self:custom.bucket} # kanben-cloud-backups
        BucketEncryption:
          ServerSideEncryptionConfiguration:
            - ServerSideEncryptionByDefault:
                SSEAlgorithm: AES256
custom:
  customDomain:
    domainName: kan.benbru.com
    basePath: ''
    stage: ${self:provider.stage}
    createRoute53Record: true
  bucket: kanben-cloud-backups
